language: node_js
node_js:
  - "8.11.3"

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

deploy:
  - provider: script
    skip_cleanup: true
    script: ng build --prod && firebase deploy --token $FIREBASE_TOKEN -P dev
    on:
      branch: dev
  - provider: script
    skip_cleanup: true
    script: ng build --prod && firebase deploy --token $FIREBASE_TOKEN -P production
    on:
      branch: master
    
notifications:
  email:
    on_failure: change
    on_success: change
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
  